### ISSUE TITLE
copy files

### ISSUE THREAD

**Issue by rafael844** [Xteeahn/FTK-Imager-Automation#1]
Great tool. Is it able to select folders and files to acquire at once ??

Thank you.

**Comment by Xteeahn** [comment]
Yeah the tool reads folder paths from a text line that you would like to have imaged and goes through the process of adding them to FTK imager and then proceeds to image them. I've updated the Ïmaging Notes Template" file which should make running this script a bit easier. 

The script might require some debugging to work with the latest FTK version.

**Comment by rafael844** [comment]
But can it read multiple folders and specific files and create a single ad1, or It creates multiple ad01?

**Comment by Xteeahn** [comment]
You can do both, either create an AD1 with one or multiple folder paths or create multiple AD1's with one or multiple folder paths. This makes life easier when doing network collections for example.

FTK imager does not support adding filepaths to the custom content images only folder paths are accepted. You can however add filenames to the filter so only files with a specific filename or extension get added. I didn't add this to the script.

If you look at the script it just follows keystrokes so it's really easy to add new things even if don't have great programming skills.

**Comment by rafael844** [comment]
Yes, its really a very good script, very clean and easy to read. The bad is that Im not such a programmer, but Ill try to figure it out. Any clue about how to, after set the folder, make it go to the right file in the file list window??

**Comment by rafael844** [comment]
Other thing, is it possible to copy specific folders/files in logical or physical mode, without any human iteration?? I just saw that with target (Contents of a folder) it changes the last accessed date.

**Comment by Xteeahn** [comment]
What do you mean with "make it go to the right file in the file list window??"? Do you want to have the file list window highlighted?

It is possible to do logical's and physicals without human iteration when the drives are already connected. Just like for the targeted collections you can create a .bat file that contains the instructions for the queue e.g. 
"D:\FTKAutomater.exe"  -p "D:\SourcePaths1.txt" -t "targeted" -c "Project test" -ev "DFT-0001" -e "Fred" -n "Project Name: Project test; " -d "D:\ " -f "3" -s "1024" -co "0"  
"D:\FTKAutomater.exe"  -p "D:\SourcePaths2.txt" -t "targeted" -c "Project test" -ev "DFT-0001" -e "Fred" -n "Project Name: Project test; " -d "D:\ " -f "2" -s "1024" -co "0"  
Just run the batch file and the script will iterate through the lines.

**Comment by rafael844** [comment]
> What do you mean with "make it go to the right file in the file list window??"? Do you want to have the file list window highlighted?

Yes, for example, if I have a folder with 10.000 files but I just want to collect 5, is it possible to get just these files? I cant figure a way to automate put the folder in ftk and then run through the file list to select just the ones I want.

> is possible to do logical's and physicals without human iteration when the drives are already connected. Just like for the targeted collections you can create a .bat file that contains the instructions for the queue e.g.

 I did this, it worked fine, its easy to understand your scrpt.

**Comment by Xteeahn** [comment]
ah right I think this could work if you use the filter option within FTK. So basically I would have a text file with a single folder (or several depending on what you want) and then another text file for all the files that would need to be added to the filter.

I'm not sure if you can get to the filter menu by just using keys, if so then this should be fairly easy to program.

**Comment by rafael844** [comment]
I just saw that, you could create a "new" filter and edit, but ftk mess with the path, if I want one file in F:\D2\CY\TEXT_DOCUMENT.TXT, the path for "logical drive" must be F:\:DEFT-Z [NTFS]|[root]|D2|CY|TEXT_DOCUMENT.TXT|* and for "content of a folder" CY:F:\D2\CY|TEXT_DOCUMENT.TXT|*
I dont think it could be changed.

**Comment by Xteeahn** [comment]
Yeah I noticed that too. I have updated the script and it should work now. 
I did quite some debugging and I updated the imaging notes template so you should be able to just use the template to run the script.

**Comment by rafael844** [comment]
Thank you very much, its working great, copying files and folders.
 Im just having troubles with UTF-8, using notepad and setting from ansi to utf8, its not getting the accents right, Pregão, remoção... are wrong, but ill figure it out.

I had to put and extra time after line 111  **pyautogui.hotkey('alt', 'f')**. It was too fast while I was getting folders from network (\\10.200.51.134\myfolder\subfolder) and it is a little slow to process the folder to ftk.

Thank you, great automation!

**Comment by rafael844** [comment]
As I could see, I couldnt use accent becouse the lack of support of pyautogui.typewrite(). In trying to change to something like:
```
pyperclip.copy(str(line))
pyautogui.hotkey("ctrl", "v")
```
And other variations, but no success. If I do it, Ill post here.

Update:
```
                pyperclip.copy((str(line)).replace("\n", ""))
                pyautogui.hotkey("ctrl", "v")
                pyautogui.hotkey('alt', 'f')
```

Now its running perfectly, thank you for all your support and nice automation!

**Comment by Xteeahn** [comment]
Nice implementation! Glad you like the script and everything works for you!
